### ISSUE TITLE
`SET` and `disable_ddl_transaction!`

### ISSUE THREAD

**Issue by pirj** [doctolib/safe-pg-migrations#34]
Those two don't play too well together when used via PgBouncer in transactional pooling mode.
Transactional pooling mode is the default for server-side (Postgres-side) PgBouncer installation on Heroku.

`SET statement_timeout`/`CREATE INDEX CONCURRENTLY` and reset of `statement_timeout` could run in three different server connections. Because of `disable_ddl_transaction!`. There are two problems here:
 - unsettling `statement_timeout` has no effect on `CREATE INDEX CONCURRENTLY`'s timeout if they are executed in different server connections
 - we leave a connection hanging in PgBouncer's pool with unset `statement_timeout`

It makes sense to mention that somewhere in the documentation.

I can handle sending a PR if you confirm and approve the problem.

**Comment by rchoquet** [comment]
Hey @pirj.

I think that the problem is even more global. Our approach is to [disable transaction for all migrations](https://github.com/doctolib/safe-pg-migrations/blob/282bcee925c92f888e35dbcd7cd02b958971bcbb/lib/safe-pg-migrations/base.rb#L82) in order to release locks as soon as possible.
So, unless PgBouncer is used in session pooling mode, I would advise to not use _safe-pg-migrations_ with it.

Thanks for the gotcha, and feel free to submit a PR!
