### ISSUE TITLE
Option to disable IdempotentStatements?

### ISSUE THREAD

**Issue by jordan-brough** [doctolib/safe-pg-migrations#60]
Would you be open to adding an option to disable `IdempotentStatements`?

Idempotency is great, but the [current code](https://github.com/doctolib/safe-pg-migrations/blob/v1.3.0/lib/safe-pg-migrations/plugins/idem_potent_statements.rb) doesn't go quite far enough currently to ensure actual idempotence imo. E.g. it only verifies that a column _name_ exists, not that it matches the column being requested.  I know I've made mistakes along those lines in the past, and I'd rather get an error message instead of having it be ignored.

Are you using the idempotency approach in general to lessen the effect of disabling transactional migrations? Are there other aspects I'm not thinking about?

**Comment by ThHareau** [comment]
Hello Jordan; thanks for your issue. 

I understand your point, we can make the module optional however I only see this as a workaround; the ideal solution would be to fix module itself.
What I propose is to adapt the code to make it optional first (I wouldn't be able to do it until next week, feel free to submit a PR if you need it sooner). 

More importantly, I think we should list the cases where the idempotency is not good enough; could you please list your examples in this issue? We should try to fix those.

**Comment by ThHareau** [comment]
Hi @jordan-brough, 

I did a test last week to improve IdempotentStatements for add_index, you can see the result in this PR: https://github.com/doctolib/safe-pg-migrations/pull/66. 

It was not successful, even if the provided solution should catch most of the case, it is not perfect and will probably never be perfect.
The difficulty is to detect the difference between two indexes having the same semantic but a different syntax. Think of extra spaces, reversed where clauses, …

This is true for indexes, but also column and table creation.

---
We initially created IdempotentStatements because we needed to disable DDL transactions for concurrent index creations. 
The goal was to be able to replay immediately a migration that failed after a lock timeout. An example would be a migration adding a column with an index. The migration would fail because it cannot acquire the lock, so we need some idempotence to be able to replay it.

The goal is so to be able to execute twice the same migration in a row. We are pretty satisfied with the behavior of the gem so far on that aspect.

---

For these reasons, we have decided not to continue in this direction, and we won't pursue the effort in making the statements perfectly idempotent. It would be many efforts for little benefits.

---

Regarding your initial request, you can actually already do it, by monkey patching the variable [SafePgMigrations::PLUGINS](https://github.com/doctolib/safe-pg-migrations/blob/master/lib/safe-pg-migrations/base.rb#L15). If you are using rails, create the file `config/initializers/safe_pg_migrations.rb` and tweak the variable: 
```rb
SafePgMigrations::PLUGINS -= [SafePgMigrations::IdemPotentStatements, SafePgMigrations::StatementRetrier]
```

I would advise to also disable the `StatementRetrier` plugin, I doubt you would obtain any result without idempotence.
